source 'https://rubygems.org'
ruby '2.3.0'

gem 'rails', '4.2.6'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'sidekiq'
gem 'sidekiq-scheduler', '~> 2.0'

gem 'bootstrap-sass', '~> 3.3.1'
gem 'sass-rails', github: 'rails/sass-rails'
gem 'autoprefixer-rails'
gem 'jquery-rails'
gem 'coffee-rails', '~> 4.1.0'

group :test do
  gem "rspec"
  gem 'rspec-rails', '~> 3.5'
  gem 'rspec-sidekiq'
  gem 'rspec_junit_formatter', '0.2.2'
  gem 'database_cleaner'
  gem 'shoulda', '~> 3.5'
  gem 'shoulda-matchers', '~> 2.0'
  gem 'json_spec'
  gem 'timecop'
  gem 'faker'
  gem 'guard-rspec', require: false
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
