source 'https://rubygems.org'
ruby '2.3.0'

gem 'rails', '4.2.6'
gem 'bootstrap-sass', '~> 3.3.1'
gem 'sass-rails', github: 'rails/sass-rails'
gem 'autoprefixer-rails'
gem 'jquery-rails'
gem 'coffee-rails', '~> 4.1.0'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]